const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{DatabaseSync}=require('node:sqlite');
const source=fs.readFileSync('workers/quanta-phi-ledger/worker.js','utf8');
function fixture(){
 const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync('quant-transfer-schema.sql','utf8'));
 sqlite.exec(`CREATE VIEW quant_wallet_balances AS SELECT w.wallet_id,COALESCE((SELECT SUM(delta) FROM quant_ledger_entries WHERE wallet_id=w.wallet_id),0)+COALESCE((SELECT legacy_amount FROM quant_legacy_migrations WHERE wallet_id=w.wallet_id),0) balance FROM quant_wallets w;
 CREATE TABLE unified_wallet_state(user_id TEXT PRIMARY KEY,infinity_balance INTEGER NOT NULL DEFAULT 0,created_at INTEGER,updated_at INTEGER);
 CREATE TABLE unified_token_records(token_id TEXT PRIMARY KEY,user_id TEXT,token_type TEXT,source TEXT,data_json TEXT,provenance_hash TEXT UNIQUE,created_at INTEGER);
 CREATE TABLE unified_wallet_events(event_id TEXT PRIMARY KEY,idempotency_key TEXT UNIQUE,user_id TEXT,asset_code TEXT,event_type TEXT,amount INTEGER,balance_after INTEGER,reference_id TEXT,metadata_json TEXT,created_at INTEGER);
 INSERT INTO quant_wallets(wallet_id,user_id) VALUES('qw_test','user_test');
 INSERT INTO unified_wallet_state VALUES('user_test',98,0,0);
 INSERT INTO quant_legacy_migrations VALUES('legacy','qw_test',79,'legacyhash',CURRENT_TIMESTAMP);`);
 let fail=false;
 const DB={prepare(sql){return{args:[],bind(...args){this.args=args;return this},async run(){return sqlite.prepare(sql).run(...this.args)},async first(){return sqlite.prepare(sql).get(...this.args)||null},async all(){return {results:sqlite.prepare(sql).all(...this.args)}},sql}},async batch(items){sqlite.exec('BEGIN');try{for(let i=0;i<items.length;i++){if(fail&&i===5)throw Error('simulated crash');sqlite.prepare(items[i].sql).run(...items[i].args)}sqlite.exec('COMMIT')}catch(e){sqlite.exec('ROLLBACK');throw e}}};
 const context={crypto,TextEncoder,Response,URL,console};vm.createContext(context);vm.runInContext(source.replace('export default {','const worker = {')+'\nglobalThis.api={commitSearchPair,ensureSearchOutbox,drainSearchOutbox,worker};',context);
 const item={user_id:'user_test',wallet_id:'qw_test',search_id:'search_012345678901234567890',query_text:'oranges',credit_query:'oranges',client_created_at:'2026-10-03',created_at:Date.now()};
 return {sqlite,env:{DB},api:context.api,item,setFail:v=>fail=v};
}
test('paired credits and history commit once even on concurrent retry',async()=>{const f=fixture();await f.api.ensureSearchOutbox(f.env);await Promise.all([f.api.commitSearchPair(f.env,f.item),f.api.commitSearchPair(f.env,f.item)]);await f.api.commitSearchPair(f.env,f.item);assert.equal(f.sqlite.prepare('SELECT infinity_balance FROM unified_wallet_state').get().infinity_balance,99);assert.equal(f.sqlite.prepare('SELECT balance FROM quant_wallet_balances').get().balance,80);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM unified_wallet_events').get().n,2);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM quanta_search_journal').get().n,1)});
test('interrupted pair rolls back; server outbox completes after browser disappears',async()=>{const f=fixture();await f.api.ensureSearchOutbox(f.env);f.sqlite.prepare("INSERT INTO quanta_search_outbox(user_id,search_id,wallet_id,query_text,credit_query,status,created_at,updated_at) VALUES(?,?,?,?,?,'PENDING',?,?)").run(f.item.user_id,f.item.search_id,f.item.wallet_id,'oranges','oranges',Date.now(),Date.now());f.setFail(true);await assert.rejects(f.api.commitSearchPair(f.env,f.item));assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM quant_mints').get().n,0);assert.equal(f.sqlite.prepare('SELECT infinity_balance FROM unified_wallet_state').get().infinity_balance,98);assert.equal(f.sqlite.prepare('SELECT status FROM quanta_search_outbox').get().status,'PENDING');f.setFail(false);await f.api.drainSearchOutbox(f.env);assert.equal(f.sqlite.prepare('SELECT status FROM quanta_search_outbox').get().status,'COMMITTED');assert.equal(f.sqlite.prepare('SELECT balance FROM quant_wallet_balances').get().balance,80);assert.equal(f.sqlite.prepare('SELECT infinity_balance FROM unified_wallet_state').get().infinity_balance,99)});
test('normal bearer token reaches identity lookup and .net CORS is supported',async()=>{const f=fixture();let lookedUp=false;f.env.IDENTITY_DB={prepare(){return{bind(){return this},async first(){lookedUp=true;return null}}}};const r=await f.api.worker.fetch(new Request('https://ledger/v1/quants/state',{headers:{Origin:'https://quantaphi.net',Authorization:'Bearer sq_'+ 'a'.repeat(40)}}),f.env);assert.equal(lookedUp,true);assert.equal((await r.json()).error,'invalid_device_token');assert.equal(r.headers.get('access-control-allow-origin'),'https://quantaphi.net')});
test('research history survives browser loss and identical saves do not duplicate revisions',async()=>{const f=fixture();f.env.IDENTITY_DB={prepare(){return{bind(){return this},async first(){return {user_id:'user_test'}}}}};await f.api.ensureSearchOutbox(f.env);await f.api.commitSearchPair(f.env,f.item);const headers={Origin:'https://quantaphi.net',Authorization:'Bearer sq_'+'a'.repeat(40),'Content-Type':'application/json'},research={id:'local-token',query:'oranges',websiteUrl:'https://example.test/oranges',payload:{overview:'Saved research',sources:[]},stage:'research'};for(let i=0;i<2;i++){const r=await f.api.worker.fetch(new Request('https://ledger/v1/quants/research',{method:'POST',headers,body:JSON.stringify({search_id:f.item.search_id,research})}),f.env);assert.equal(r.status,200)}const r=await f.api.worker.fetch(new Request('https://ledger/v1/quants/history',{headers}),f.env),data=await r.json();assert.equal(JSON.parse(data.tokens[0].research_json).payload.overview,'Saved research');assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM quanta_research_revisions').get().n,1);assert.equal(f.sqlite.prepare('SELECT balance FROM quant_wallet_balances').get().balance,80)});


test('cloud history restore stays off focus and wallet lifecycle events',()=>{
  const sync=fs.readFileSync(path.join(__dirname,'../search-wallet-sync.js'),'utf8');
  const page=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
  assert.match(sync,/for\(const event of \['load','online','focus'\]\)global\.addEventListener\(event,flush\)/);
  assert.doesNotMatch(sync,/\['load','online','focus'\][^\n]*restoreCloudHistory/);
  assert.match(page,/QuantaInfinityCredit\?\.restoreHistory\?\.\(\)\.then\(render\)/);
});
