INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (1,'Energy & electricity');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (2,'Technology & computing');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (3,'Art & museums');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (4,'Ghosts & hauntings');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (5,'Parapsychology & strange experiments');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (6,'Inventors & patents');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (7,'Astronomy & space');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (8,'Hidden military history');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (9,'Spycraft & intelligence');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (10,'Archaeology');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (11,'Ancient civilizations');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (12,'Medicine & medical history');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (13,'Biology & evolution');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (14,'Chemistry & materials');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (15,'Physics & mathematics');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (16,'Earth & geology');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (17,'Oceans & deep sea');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (18,'Weather & natural disasters');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (19,'Accidents & engineering failures');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (20,'Music & musicians');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (21,'Film & television');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (22,'Books & literature');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (23,'Royalty & presidents');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (24,'Crime & unsolved cases');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (25,'Hidden architecture & unusual buildings');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (26,'Transportation & flight');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (27,'Business & corporate history');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (28,'Remarkable human feats');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (29,'Animals & unusual behavior');
INSERT OR IGNORE INTO rr_sectors(id,name) VALUES (30,'Everyday objects & forgotten origins');
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Hydrogen','hydrogen','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Helium','helium','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Lithium','lithium','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Petroleum','petroleum','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Crude oil','crude oil','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Natural gas','natural gas','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Coal','coal','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Electricity','electricity','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Solar energy','solar energy','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Wind energy','wind energy','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Hydropower','hydropower','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Nuclear fission','nuclear fission','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Nuclear fusion','nuclear fusion','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Geothermal energy','geothermal energy','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Tidal power','tidal power','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Wave power','wave power','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Biomass energy','biomass energy','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Biofuels','biofuels','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Biodiesel','biodiesel','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Ethanol fuel','ethanol fuel','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Kerosene','kerosene','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Gasoline','gasoline','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Diesel fuel','diesel fuel','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Propane','propane','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Butane','butane','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Methane','methane','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Ethane','ethane','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Ammonia fuel','ammonia fuel','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Hydrogen fuel cells','hydrogen fuel cells','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Lithium-ion batteries','lithium ion batteries','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Lead-acid batteries','lead acid batteries','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Sodium-ion batteries','sodium ion batteries','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Solid-state batteries','solid state batteries','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Flow batteries','flow batteries','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Supercapacitors','supercapacitors','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Flywheel energy storage','flywheel energy storage','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Pumped-storage hydroelectricity','pumped storage hydroelectricity','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Compressed-air energy storage','compressed air energy storage','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Thermal energy storage','thermal energy storage','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Molten salt storage','molten salt storage','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Electric generators','electric generators','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Alternators','alternators','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Electric motors','electric motors','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Transformers','transformers','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Power transmission','power transmission','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'High-voltage direct current','high voltage direct current','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Power substations','power substations','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Smart grids','smart grids','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Microgrids','microgrids','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Electric meters','electric meters','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Electric arcs','electric arcs','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Lightning','lightning','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Electromagnetic induction','electromagnetic induction','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Piezoelectricity','piezoelectricity','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Thermoelectricity','thermoelectricity','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Photovoltaics','photovoltaics','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Solar thermal power','solar thermal power','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Concentrated solar power','concentrated solar power','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Wind turbines','wind turbines','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Offshore wind farms','offshore wind farms','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Hydroelectric dams','hydroelectric dams','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Run-of-river hydropower','run of river hydropower','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Pelton turbines','pelton turbines','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Francis turbines','francis turbines','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Steam turbines','steam turbines','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Gas turbines','gas turbines','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Combined-cycle power plants','combined cycle power plants','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Heat engines','heat engines','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Internal combustion engines','internal combustion engines','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Stirling engines','stirling engines','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Fuel combustion','fuel combustion','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Thermodynamics','thermodynamics','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Entropy','entropy','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Heat transfer','heat transfer','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Heat pumps','heat pumps','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'District heating','district heating','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Combined heat and power','combined heat and power','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Waste heat recovery','waste heat recovery','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Power plant cooling','power plant cooling','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Nuclear reactors','nuclear reactors','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Uranium','uranium','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Plutonium','plutonium','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Thorium','thorium','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Heavy water','heavy water','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Radiation shielding','radiation shielding','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Radioisotope generators','radioisotope generators','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Radioactive decay','radioactive decay','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Fusion tokamaks','fusion tokamaks','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Stellarators','stellarators','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Plasma confinement','plasma confinement','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Magnetohydrodynamics','magnetohydrodynamics','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Electrolysis','electrolysis','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Hydrogen storage','hydrogen storage','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Hydrogen pipelines','hydrogen pipelines','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Carbon capture','carbon capture','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Oil drilling','oil drilling','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Oil refineries','oil refineries','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Shale gas','shale gas','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Coal mining','coal mining','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Natural gas liquefaction','natural gas liquefaction','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Petrochemical plants','petrochemical plants','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Energy conservation','energy conservation','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Energy efficiency','energy efficiency','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Energy auditing','energy auditing','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Peak demand','peak demand','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Demand response','demand response','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Blackouts','blackouts','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Grid frequency','grid frequency','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Electric resistance','electric resistance','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Current and voltage','current and voltage','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Electrical conductors','electrical conductors','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Semiconductors','semiconductors','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Superconductors','superconductors','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Power electronics','power electronics','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Inverters','inverters','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Rectifiers','rectifiers','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Circuit breakers','circuit breakers','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Grounding systems','grounding systems','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Energy markets','energy markets','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Energy history','energy history','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Energy shortages','energy shortages','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Energy transitions','energy transitions','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (1,'Battery recycling','battery recycling','editorial_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (14,'Hydrogen','hydrogen','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (15,'Hydrogen','hydrogen','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (4,'Ghosts','ghosts','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (5,'Ghosts','ghosts','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (23,'Ghosts','ghosts','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (24,'Ghosts','ghosts','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (14,'Helium','helium','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (7,'Helium','helium','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (15,'Helium','helium','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (14,'Energy','energy','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (15,'Energy','energy','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (6,'Tesla','tesla','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (2,'Radio','radio','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (15,'Quantum','quantum','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (14,'Quantum','quantum','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (7,'Space','space','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (7,'Moon','moon','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (7,'Mars','mars','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (7,'Saturn','saturn','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (15,'Saturn','saturn','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (7,'Comets','comets','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (16,'Meteors','meteors','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (7,'Stars','stars','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (17,'Oceans','oceans','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (17,'Shipwrecks','shipwrecks','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (26,'Pirates','pirates','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (16,'Pirates','pirates','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (11,'Atlantis','atlantis','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (10,'Archaeology','archaeology','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (11,'Archaeology','archaeology','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (11,'Pyramids','pyramids','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (10,'Mummies','mummies','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (13,'Dinosaurs','dinosaurs','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (13,'Fossils','fossils','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (16,'Volcanoes','volcanoes','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (16,'Earthquakes','earthquakes','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (18,'Hurricanes','hurricanes','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (18,'Lightning','lightning','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (18,'Weather','weather','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (16,'Wilderness','wilderness','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (29,'Animals','animals','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (13,'Animals','animals','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (17,'Whales','whales','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (29,'Octopuses','octopuses','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (29,'Birds','birds','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (13,'Insects','insects','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (13,'Evolution','evolution','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (13,'DNA','dna','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (12,'Medicine','medicine','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (14,'Medicine','medicine','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (12,'Vaccines','vaccines','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (14,'Chemistry','chemistry','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (15,'Chemistry','chemistry','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (14,'Elements','elements','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (15,'Elements','elements','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (14,'Gold','gold','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (27,'Gold','gold','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (14,'Silver','silver','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (27,'Silver','silver','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (14,'Uranium','uranium','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (15,'Uranium','uranium','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (15,'Magnetism','magnetism','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (15,'Radiation','radiation','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (12,'Radiation','radiation','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (6,'Robots','robots','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (2,'Robots','robots','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (2,'Computers','computers','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (6,'Computers','computers','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (2,'Internet','internet','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (6,'Inventions','inventions','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (6,'Patents','patents','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (27,'Patents','patents','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (26,'Automobiles','automobiles','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (26,'Trains','trains','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (26,'Aircraft','aircraft','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (26,'Balloons','balloons','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (7,'Rockets','rockets','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (7,'Satellites','satellites','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (25,'Bridges','bridges','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (19,'Bridges','bridges','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (25,'Tunnels','tunnels','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (25,'Castles','castles','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (23,'Palaces','palaces','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (11,'Temples','temples','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (25,'Cities','cities','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (16,'Islands','islands','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (16,'Caves','caves','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (28,'Expeditions','expeditions','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (28,'Explorers','explorers','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (9,'Spies','spies','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (9,'Codes','codes','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (2,'Codes','codes','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (9,'Intelligence','intelligence','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (8,'Intelligence','intelligence','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (8,'Wars','wars','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (8,'Battles','battles','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (11,'Empires','empires','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (23,'Empires','empires','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (23,'Presidents','presidents','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (23,'Royalty','royalty','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (6,'Inventors','inventors','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (15,'Scientists','scientists','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (3,'Artists','artists','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (3,'Paintings','paintings','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (3,'Museums','museums','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (20,'Music','music','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (20,'Pianos','pianos','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (20,'Recordings','recordings','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (21,'Cinema','cinema','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (21,'Television','television','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (22,'Literature','literature','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (22,'Manuscripts','manuscripts','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (4,'Folklore','folklore','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (4,'Legends','legends','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (11,'Mythology','mythology','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (24,'Crime','crime','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (9,'Crime','crime','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (24,'Mysteries','mysteries','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (24,'Disappearances','disappearances','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (9,'Disappearances','disappearances','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (10,'Treasure','treasure','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (23,'Treasure','treasure','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (24,'Hoaxes','hoaxes','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (19,'Disasters','disasters','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (5,'Experiments','experiments','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (6,'Discoveries','discoveries','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (27,'Discoveries','discoveries','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (6,'Machines','machines','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_topics(sector_id,term,normalized,origin,reviewed) VALUES (30,'Oddities','oddities','legacy_index_seed',1);
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (1,'Mystery');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (2,'Suspense');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (3,'Adventure');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (4,'History');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (5,'Origins');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (6,'Hidden evidence');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (7,'Lost inventions');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (8,'Forgotten people');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (9,'Strange experiments');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (10,'Scientific breakthroughs');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (11,'Unsolved questions');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (12,'Historical myths');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (13,'Near disasters');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (14,'Unexpected discoveries');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (15,'Ancient clues');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (16,'Rare artifacts');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (17,'Folklore and legends');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (18,'Secret operations');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (19,'Impossible coincidences');
INSERT OR IGNORE INTO rr_refinements(id,label) VALUES (20,'Rediscovered treasures');
INSERT OR IGNORE INTO rr_genres(id,label,directive) VALUES (1,'Mystery','Unfold the unexplained question while distinguishing established facts from unresolved claims');
INSERT OR IGNORE INTO rr_genres(id,label,directive) VALUES (2,'Suspense','Build tension through the real sequence of events, without inventing danger or dialogue');
INSERT OR IGNORE INTO rr_genres(id,label,directive) VALUES (3,'Adventure','Follow the real journey, investigation or discovery without fictionalizing evidence');
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('history.com','https://www.history.com/articles',7);
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('si.edu','https://www.si.edu/stories',2);
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('invention.si.edu','https://invention.si.edu/',2);
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('americanhistory.si.edu','https://americanhistory.si.edu/explore/topics/invention-and-innovation',2);
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('blogs.loc.gov','https://blogs.loc.gov/',1);
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('archives.gov','https://www.archives.gov/',1);
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('smithsonianmag.com','https://www.smithsonianmag.com/history/',7);
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('sciencehistory.org','https://www.sciencehistory.org/',2);
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('nps.gov','https://www.nps.gov/subjects/history/index.htm',1);
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('nasa.gov','https://www.nasa.gov/',1);
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('nationalww2museum.org','https://www.nationalww2museum.org/',2);
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('computerhistory.org','https://computerhistory.org/',2);
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('patents.google.com','https://patents.google.com/',1);
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('pbs.org','https://www.pbs.org/',7);
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('rsc.org','https://www.rsc.org/periodic-table',2);
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('acs.org','https://www.acs.org/',3);
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('nobelprize.org','https://www.nobelprize.org/',1);
INSERT OR IGNORE INTO rr_sources(domain,homepage,source_class) VALUES ('sciencemuseumgroup.org.uk','https://www.sciencemuseumgroup.org.uk/',2);
