const ALLOWED_ORIGINS = new Set([
  "https://www-infinity4.github.io",
  "https://quantaphi.org",
  "https://www.quantaphi.org",
  "https://infinity-rogers.marvaseater.workers.dev",
  "https://infinity-work-tickets.marvaseater.workers.dev",
  "http://localhost:8000",
  "http://127.0.0.1:8000"
]);
function clean(v,max=12000){return typeof v==="string"?v.trim().slice(0,max):""}
function cors(req){const o=req.headers.get("Origin")||"";return ALLOWED_ORIGINS.has(o)?{"Access-Control-Allow-Origin":o,"Access-Control-Allow-Headers":"Content-Type","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Max-Age":"86400",Vary:"Origin"}:{}}
function json(req,b,status=200){return new Response(JSON.stringify(b),{status,headers:{...cors(req),"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}})}
function allowed(req){return ALLOWED_ORIGINS.has(req.headers.get("Origin")||"")}
async function readBody(req){if(!req.headers.get("Content-Type")?.toLowerCase().includes("application/json"))throw new Error("json_required");return req.json()}
async function hash(v){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function token(){return crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().replaceAll("-","")}
function ticketId(){const d=new Date().toISOString().slice(0,10).replaceAll("-","");return "IW-"+d+"-"+crypto.randomUUID().slice(0,8).toUpperCase()}
function publicTicket(r){if(!r)return null;let context={};try{context=JSON.parse(r.context_json||"{}")}catch{}return{id:r.id,source_app:r.source_app,source_url:r.source_url,repository:r.repository,title:r.title,request:r.request,storyboard:r.storyboard,context,status:r.status,claimed_by:r.claimed_by,result_summary:r.result_summary||"",result_url:r.result_url||"",created_at:r.created_at,updated_at:r.updated_at,completed_at:r.completed_at||null}}
function handoffText(t){return ["Infinity Work Ticket "+t.id,"Title: "+t.title,t.repository?"Repository: "+t.repository:"",t.source_url?"Source: "+t.source_url:"","","REQUEST",t.request,"",t.storyboard?"AI STORYBOARD / BUILD NOTES\n"+t.storyboard:"","","Please treat this as a persistent work order. Read the full ticket context, carry out the work using authorized tools, and update the ticket status/result when the Infinity Work Tickets app is available. Do not claim repository or deployment changes unless verified."].filter(Boolean).join("\n")}

async function allowCreate(req,env,ownerToken=''){
 if(ownerToken){const known=await env.WORK_DB.prepare('SELECT id FROM work_tickets WHERE owner_hash=?1 LIMIT 1').bind(await hash(ownerToken)).first();if(known)return true;}
 const ip=req.headers.get("CF-Connecting-IP")||"unknown",day=new Date().toISOString().slice(0,10),key=await hash("create|"+ip+"|"+day),now=Date.now(),expires=now+86400000;
 const row=await env.WORK_DB.prepare("SELECT request_count,expires_at FROM rate_windows WHERE window_key=?1").bind(key).first();
 if(row&&Number(row.expires_at)>now&&Number(row.request_count)>=10)return false;
 await env.WORK_DB.prepare("INSERT INTO rate_windows(window_key,request_count,expires_at) VALUES(?1,1,?2) ON CONFLICT(window_key) DO UPDATE SET request_count=CASE WHEN expires_at>?3 THEN request_count+1 ELSE 1 END,expires_at=CASE WHEN expires_at>?3 THEN expires_at ELSE ?2 END").bind(key,expires,now).run();
 return true;
}
async function listNotifications(req,env,b){
 const ownerToken=clean(b.owner_token,300);if(!ownerToken)return json(req,{ok:false,error:"owner_token_required"},401);
 const rows=await env.WORK_DB.prepare("SELECT id,title,status,claimed_by,result_summary,result_url,updated_at,completed_at FROM work_tickets WHERE owner_hash=?1 ORDER BY updated_at DESC LIMIT 100").bind(await hash(ownerToken)).all();
 return json(req,{ok:true,notifications:(rows.results||[]).map(r=>({id:r.id,type:r.status==="complete"?"ticket_complete":r.status==="claimed"||r.status==="working"?"ticket_progress":"ticket_update",title:r.title,status:r.status,claimed_by:r.claimed_by,result_summary:r.result_summary,result_url:r.result_url,updated_at:r.updated_at,completed_at:r.completed_at||null}))});
}

async function createTicket(req,env,b){
 const existingOwner=clean(b.owner_token,300),submission=clean(b.context?.submission_id,100);
 if(existingOwner&&submission){const row=await env.WORK_DB.prepare("SELECT * FROM work_tickets WHERE owner_hash=?1 AND json_extract(context_json,'$.submission_id')=?2 LIMIT 1").bind(await hash(existingOwner),submission).first();if(row)return json(req,{ok:true,ticket:publicTicket(row),deduplicated:true});}
 if(!(await allowCreate(req,env,existingOwner)))return json(req,{ok:false,error:"rate_limited",message:"Ticket creation limit reached for today."},429);
 const requestText=(typeof (b.request||b.input)==="string"?(b.request||b.input).trim():"");if(!requestText)return json(req,{ok:false,error:"request_required"},400);
 let ownerToken=clean(b.owner_token,300),ownerTokenCreated=false;if(!ownerToken){ownerToken=token();ownerTokenCreated=true}
 const handoffToken=token(),id=ticketId(),now=Date.now(),title=clean(b.title,180)||requestText.slice(0,120),sourceApp=clean(b.source_app,100)||"Omni Phi",sourceUrl=clean(b.source_url,1000),repository=clean(b.repository,220),storyboard=clean(b.storyboard,24000),contextJson=JSON.stringify(b.context&&typeof b.context==="object"?b.context:{});
 const sql="INSERT INTO work_tickets (id,owner_hash,handoff_hash,source_app,source_url,repository,title,request,storyboard,context_json,status,claimed_by,created_at,updated_at,completed_at,handoff_expires_at,result_summary,result_url) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,'draft','',?11,?11,NULL,?12,'','')";
 await env.WORK_DB.prepare(sql).bind(id,await hash(ownerToken),await hash(handoffToken),sourceApp,sourceUrl,repository,title,requestText,storyboard,contextJson,now,now+30*24*60*60*1000).run();
 const t={id,source_app:sourceApp,source_url:sourceUrl,repository,title,request:requestText,storyboard,context:b.context||{},status:"draft",claimed_by:"",result_summary:"",result_url:"",created_at:now,updated_at:now,completed_at:null};
 return json(req,{ok:true,ticket:t,owner_token:ownerTokenCreated?ownerToken:undefined,handoff_token:handoffToken,handoff_text:handoffText(t)})
}
async function getTicket(req,env,b){const id=clean(b.id,80);if(!id)return json(req,{ok:false,error:"id_required"},400);const ownerToken=clean(b.owner_token,300),handoffToken=clean(b.handoff_token,300);if(!ownerToken&&!handoffToken)return json(req,{ok:false,error:"authorization_required"},401);const row=await env.WORK_DB.prepare("SELECT * FROM work_tickets WHERE id=?1").bind(id).first();if(!row)return json(req,{ok:false,error:"ticket_not_found"},404);const goodOwner=ownerToken&&(await hash(ownerToken))===row.owner_hash;const goodHandoff=handoffToken&&(await hash(handoffToken))===row.handoff_hash&&Date.now()<=Number(row.handoff_expires_at||0);if(!goodOwner&&!goodHandoff)return json(req,{ok:false,error:"not_authorized"},403);const t=publicTicket(row);return json(req,{ok:true,ticket:t,handoff_text:handoffText(t)})}
async function listTickets(req,env,b){const ownerToken=clean(b.owner_token,300);if(!ownerToken)return json(req,{ok:false,error:"owner_token_required"},401);const rows=await env.WORK_DB.prepare("SELECT * FROM work_tickets WHERE owner_hash=?1 ORDER BY updated_at DESC LIMIT 100").bind(await hash(ownerToken)).all();return json(req,{ok:true,tickets:(rows.results||[]).map(publicTicket)})}
async function updateTicket(req,env,b){const id=clean(b.id,80),ownerToken=clean(b.owner_token,300);if(!id||!ownerToken)return json(req,{ok:false,error:"id_and_owner_token_required"},400);const row=await env.WORK_DB.prepare("SELECT * FROM work_tickets WHERE id=?1").bind(id).first();if(!row)return json(req,{ok:false,error:"ticket_not_found"},404);if((await hash(ownerToken))!==row.owner_hash)return json(req,{ok:false,error:"not_authorized"},403);const title=clean(b.title,180)||row.title,requestText=(typeof b.request==="string"?b.request.trim():"")||row.request,storyboard=typeof b.storyboard==="string"?clean(b.storyboard,24000):row.storyboard,repository=typeof b.repository==="string"?clean(b.repository,220):row.repository,sourceUrl=typeof b.source_url==="string"?clean(b.source_url,1000):row.source_url,contextJson=b.context&&typeof b.context==="object"?JSON.stringify(b.context):row.context_json,status=["draft","ready","claimed","working","complete","blocked"].includes(b.status)?b.status:row.status,now=Date.now();await env.WORK_DB.prepare("UPDATE work_tickets SET title=?2,request=?3,storyboard=?4,repository=?5,source_url=?6,context_json=?7,status=?8,updated_at=?9 WHERE id=?1").bind(id,title,requestText,storyboard,repository,sourceUrl,contextJson,status,now).run();const fresh=await env.WORK_DB.prepare("SELECT * FROM work_tickets WHERE id=?1").bind(id).first();return json(req,{ok:true,ticket:publicTicket(fresh)})}
async function claimTicket(req,env,b){const id=clean(b.id,80),handoffToken=clean(b.handoff_token,300);if(!id||!handoffToken)return json(req,{ok:false,error:"id_and_handoff_token_required"},400);const row=await env.WORK_DB.prepare("SELECT * FROM work_tickets WHERE id=?1").bind(id).first();if(!row)return json(req,{ok:false,error:"ticket_not_found"},404);if((await hash(handoffToken))!==row.handoff_hash||Date.now()>Number(row.handoff_expires_at||0))return json(req,{ok:false,error:"not_authorized"},403);const who=clean(b.claimed_by,120)||"ChatGPT",now=Date.now();await env.WORK_DB.prepare("UPDATE work_tickets SET status='claimed',claimed_by=?2,updated_at=?3 WHERE id=?1").bind(id,who,now).run();const fresh=await env.WORK_DB.prepare("SELECT * FROM work_tickets WHERE id=?1").bind(id).first();return json(req,{ok:true,ticket:publicTicket(fresh),handoff_text:handoffText(publicTicket(fresh))})}
async function completeTicket(req,env,b){const id=clean(b.id,80),handoffToken=clean(b.handoff_token,300);if(!id||!handoffToken)return json(req,{ok:false,error:"id_and_handoff_token_required"},400);const row=await env.WORK_DB.prepare("SELECT * FROM work_tickets WHERE id=?1").bind(id).first();if(!row)return json(req,{ok:false,error:"ticket_not_found"},404);if((await hash(handoffToken))!==row.handoff_hash||Date.now()>Number(row.handoff_expires_at||0))return json(req,{ok:false,error:"not_authorized"},403);const summary=clean(b.result_summary,12000),resultUrl=clean(b.result_url,1200),now=Date.now();await env.WORK_DB.prepare("UPDATE work_tickets SET status='complete',result_summary=?2,result_url=?3,updated_at=?4,completed_at=?4 WHERE id=?1").bind(id,summary,resultUrl,now).run();return json(req,{ok:true})}
export default{async fetch(req,env){const u=new URL(req.url);if(req.method==="OPTIONS"){if(!allowed(req))return json(req,{ok:false,error:"origin_not_allowed"},403);return new Response(null,{status:204,headers:cors(req)})}if(req.method==="GET"&&u.pathname==="/health")return json(req,{ok:true,service:"infinity-work-tickets",version:"2026-09-21-handoff-notifications-1",database:Boolean(env.WORK_DB)});if(req.method!=="POST")return json(req,{ok:false,error:"not_found"},404);if(!allowed(req))return json(req,{ok:false,error:"origin_not_allowed"},403);let b;try{b=await readBody(req)}catch(e){return json(req,{ok:false,error:String(e?.message||e)},400)}if(u.pathname==="/v1/tickets/create")return createTicket(req,env,b);if(u.pathname==="/v1/tickets/get"||u.pathname==="/v1/tickets/handoff")return getTicket(req,env,b);if(u.pathname==="/v1/notifications/list")return listNotifications(req,env,b);if(u.pathname==="/v1/tickets/list")return listTickets(req,env,b);if(u.pathname==="/v1/tickets/update")return updateTicket(req,env,b);if(u.pathname==="/v1/tickets/claim")return claimTicket(req,env,b);if(u.pathname==="/v1/tickets/complete")return completeTicket(req,env,b);return json(req,{ok:false,error:"not_found"},404)}};
